set(SMARTEREYE_VERSION_MAJOR 0)
set(SMARTEREYE_VERSION_MINOR 0)
set(SMARTEREYE_VERSION_PATCH 1)
set(SMARTEREYE_VERSION_STRING ${SMARTEREYE_VERSION_MAJOR}.${SMARTEREYE_VERSION_MINOR}.${SMARTEREYE_VERSION_PATCH})
